package.name = "sonder"
package.version = "0.1.0"
package.edition = "2021"
dependencies.engine.version = "0.1.0"
dependencies.engine.path = "./engine"
dependencies.dioxus.version = ">=0.6.0,<1.0.0"
dependencies.dioxus.features = ["router", "fullstack"]
dependencies.modwire.version = ">=0.1.0,<1.0.0"
dependencies.dioxus-charts.version = ">=0.3.1,<1.0.0"
dependencies.dioxus-motion.version = "*"
dependencies.diogen.git = "https://github.com/unsudo-org/diogen"
dependencies.gloo-timers.version = "*"
dependencies.gloo-timers.features = ["futures"]
dependencies.futures-util.version = "*"
dependencies.fastrand.version = "*"
dependencies.strum.version = "*"
dependencies.strum_macros.version = "*"
dependencies.once_cell.version = "*"
dependencies.serde.version = "*"
dependencies.erased-serde.version = "*"
dependencies.reliq.version = "*"
dependencies.reliq.features = ["std"]
dependencies.thiserror.version = "*"
dependencies.web-sys.version = "*"
dependencies.web-sys.optional = true
dependencies.wasm-bindgen-futures.version = "*"
features.default = ["web"]
features.web = ["dioxus/web", "dep:web-sys"]
features.desktop = ["dioxus/desktop"]
features.mobile = ["dioxus/mobile"]
profile.wasm-dev.inherits = "dev"
profile.wasm-dev.opt-level = 1
profile.server-dev.inherits = "dev"
profile.android-dev.inherits = "dev"
